# -*- coding: utf-8 -*-
"""
InkGen Studio - Language Model (LLM) Service
=============================================

This module provides a unified service for interacting with the Google Gemini
Large Language Model (LLM).

It encapsulates the logic for API key management, request sending, and response
handling, including a key rotation mechanism to improve robustness and manage
API rate limits.

Author: Jules
Date: 2025-09-30
Version: 1.0
"""

import google.generativeai as genai
from itertools import cycle
from .config import config  # Import the global config instance

class LLMService:
    """
    A service class to manage interactions with the Gemini LLM.

    This class handles the rotation of API keys and provides a simple
    interface for generating text content based on a given prompt.
    """
    _instance = None

    def __new__(cls, *args, **kwargs):
        """
        Implements the Singleton pattern to ensure only one instance of LLMService exists.
        This prevents multiple, redundant cycles of API keys.
        """
        if not cls._instance:
            cls._instance = super(LLMService, cls).__new__(cls)
        return cls._instance

    def __init__(self):
        """
        Initializes the LLMService.

        This method sets up the API key cycle. It's designed to be called only
        once due to the Singleton pattern.
        """
        # The __init__ might be called multiple times in a Singleton pattern,
        # so we check if the initialization has already been done.
        if not hasattr(self, 'api_key_cycler'):
            if not config.api_keys:
                raise ValueError("No API keys configured in LLMService.")

            # Create an infinite iterator that cycles through the API keys.
            # This is the core of the round-robin rotation mechanism.
            self.api_key_cycler = cycle(config.api_keys)
            self.model_name = "gemini-pro" # Default model, can be made configurable later

    def _get_next_key(self) -> str:
        """
        Retrieves the next API key from the rotation.

        Returns:
            str: The next API key to be used for a request.
        """
        return next(self.api_key_cycler)

    def generate_text(self, prompt: str) -> str:
        """
        Generates text using the Gemini LLM with a rotating API key.

        Args:
            prompt (str): The input prompt to send to the language model.

        Returns:
            str: The text generated by the model.

        Raises:
            Exception: Propagates exceptions from the API call if generation fails.
        """
        try:
            # 1. Get the next API key from our rotating cycler.
            api_key = self._get_next_key()

            # 2. Configure the `genai` library with this specific key for this call.
            genai.configure(api_key=api_key)

            # 3. Instantiate the model.
            model = genai.GenerativeModel(self.model_name)

            # 4. Generate content.
            response = model.generate_content(prompt)

            return response.text

        except Exception as e:
            # In a real application, we would add more sophisticated logging here.
            print(f"Error during text generation with key ending in '...{api_key[-4:]}': {e}")
            # Depending on the error, we could implement retry logic here.
            # For now, we re-raise the exception to be handled by the caller.
            raise

# Create a single, globally accessible instance of the LLMService.
# AI agents can simply `from src.llm_service import llm_service` to use it.
llm_service = LLMService()